### ISSUE TITLE
Css/Styling

### ISSUE THREAD

**Issue by Senkua** [Senkua/Proffessional-Portfolio#4]
Finalize the styling of the page, Add modern colors, make sure colors contrast.

**Comment by itsubaidullahomer** [comment]
Choose a color palette that is pleasing to the eye and that complements your brand. There are many different color palettes available online, or you can create your own. When choosing a color palette, it is important to consider the overall mood and tone you want to create for your page. For example, if you want your page to be calming and relaxing, you might choose a palette of soft, muted colors. If you want your page to be more energetic and engaging, you might choose a palette of brighter, more vibrant colors.
Use contrasting colors to make your text and other important elements stand out. The human eye is naturally drawn to contrast, so using contrasting colors can help to make your page more visually appealing and easy to read. When choosing contrasting colors, it is important to consider the WCAG guidelines, which recommend a minimum contrast ratio of 4.5:1 for normal text and 3:1 for large text.
Use color to create a visual hierarchy on your page. Visual hierarchy is the way that you arrange the elements on your page so that they are visually appealing and easy to scan. You can use color to create a visual hierarchy by using lighter colors for background elements and darker colors for foreground elements. You can also use color to group related elements together.
Use color to add interest and excitement to your page. Color can be a great way to add interest and excitement to your page. You can use color to create patterns, borders, and other decorative elements. You can also use color to highlight important information or to create a sense of movement or excitement.

**Comment by Senkua** [comment]
wow thanks for the great feedback! I'll take this into consideration.
